"""Generate a glyph-indexed Font 0 advance table from independently checked metrics.

Requires fontTools only for this manual generation step, never at runtime.
The embedded font supplies glyph IDs, not the corrected advance values.
Unmeasured glyphs and conflicting Unicode aliases retain the original advance.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / 'resources/fonts/font0.ttf'
MEASUREMENTS = ROOT / 'tests/golden/font0-metrics/measurements.json'
OUTPUT = ROOT / 'src/font0_advance_data.hpp'
COVERAGE = ROOT / 'tests/golden/font0-metrics/embedded-font-coverage.json'


def generate() -> tuple[str, dict]:
    measured = json.loads(MEASUREMENTS.read_text(encoding='utf8'))
    if measured['unitsPerEm'] != 2048:
        raise ValueError('Expected exact 2048-unit reference metrics')
    font = TTFont(FONT)
    cmap = font.getBestCmap()
    candidates: dict[int, list[tuple[str, int]]] = {}
    absent = []
    for codepoint, measurement in measured['glyphs'].items():
        value = measurement['hmtxAdvance']
        if type(value) is not int or not 0 <= value <= 32767 or measurement['unitsPerEm'] != 2048:
            raise ValueError(f'Invalid qint16 metric for {codepoint}')
        verified = [observation for observation in measurement['observations']
                    if observation['status'] == 'validated' and abs(observation['residualDots']) <= .500001]
        if len({(v['fontWidth'], v['repeat']) for v in verified}) < 2:
            raise ValueError(f'Insufficient independent raster evidence for {codepoint}')
        scalar = int(codepoint[2:], 16)
        if scalar not in cmap:
            absent.append(codepoint)
            continue
        glyph = font.getGlyphID(cmap[scalar])
        if glyph == 0:
            raise ValueError(f'{codepoint} maps to the missing-glyph fallback')
        candidates.setdefault(glyph, []).append((codepoint, value))
    values = [-1] * font['maxp'].numGlyphs
    conflicts = {}
    for glyph, entries in candidates.items():
        advances = {advance for _, advance in entries}
        if len(advances) == 1:
            values[glyph] = advances.pop()
        else:
            conflicts[str(glyph)] = entries
    # Also protect unmeasured aliases of a measured glyph: applying a correction
    # would otherwise silently change a character with no oracle evidence.
    measured_cps = {int(cp[2:], 16) for cp in measured['glyphs']}
    unmeasured_aliases = {}
    for scalar, name in cmap.items():
        glyph = font.getGlyphID(name)
        if scalar not in measured_cps and glyph in candidates:
            unmeasured_aliases.setdefault(str(glyph), []).append(f'U+{scalar:04X}')
            values[glyph] = -1
    font_sha = hashlib.sha256(FONT.read_bytes()).hexdigest()
    measured_sha = hashlib.sha256(MEASUREMENTS.read_bytes()).hexdigest()
    lines = ['#pragma once', '', '#include <QtCore/qtypes.h>', '#include <array>', '',
             '// Generated by tools/generate_font0_advances.py; do not edit.',
             '// Exact numeric advances, independently checked against original Labelary',
             '// bitonal repeated-glyph rulers. No reference outlines or font program.',
             f'// Embedded Font 0 SHA-256: {font_sha}',
             f'// Measurement JSON SHA-256: {measured_sha}',
             '// -1 preserves the embedded design advance; zero is a valid advance.',
             'namespace QtZpl::Font0AdvanceData {',
             'inline constexpr int unitsPerEm = 2048;',
             '// R-direction nominal cell: nearest integer dot width of M.',
             f'inline constexpr qint16 nominalCellAdvance2048 = {measured["glyphs"]["U+004D"]["hmtxAdvance"]};',
             f'inline constexpr std::array<qint16, {len(values)}> advances2048 = {{']
    for start in range(0, len(values), 12):
        lines.append('    ' + ', '.join(str(v) for v in values[start:start+12]) + f', // glyphs {start}..{min(start+11,len(values)-1)}')
    lines += ['};', '} // namespace QtZpl::Font0AdvanceData', '']
    return '\n'.join(lines), {'glyphCount': len(values), 'correctedGlyphs': sum(v >= 0 for v in values),
                              'absentCodepoints': absent, 'conflictingAliases': conflicts,
                              'unmeasuredAliases': unmeasured_aliases, 'fontSha256': font_sha,
                              'glyphIds': {cp: glyph for glyph, entries in candidates.items() for cp, _ in entries}}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='verify the saved header without modifying it')
    args = parser.parse_args()
    content, report = generate()
    if args.check:
        if OUTPUT.read_text(encoding='utf8') != content:
            raise ValueError('Font 0 advance header is stale; regenerate it')
        if json.loads(COVERAGE.read_text(encoding='utf8')) != report:
            raise ValueError('Embedded font coverage is stale; regenerate it')
    else:
        OUTPUT.write_text(content, encoding='utf8', newline='\n')
        COVERAGE.write_text(json.dumps(report,indent=2)+'\n',encoding='utf8',newline='\n')
    print(json.dumps({k:v for k,v in report.items() if k!='glyphIds'}, indent=2))


if __name__ == '__main__':
    main()
