#!/usr/bin/env python3
"""Generate the native PDF417 symbol-pattern table from go-zpl's MIT source."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = PROJECT_ROOT.parent / "go-zpl" / "internal" / "pdf417" / "codewords.go"
DEFAULT_OUTPUT = PROJECT_ROOT / "src" / "pdf417_codeword_patterns.inc"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    source = args.source.read_text(encoding="utf-8")
    table = source[source.index("var codewords ="):source.index("func getCodeword")]
    values = [int(token, 16) for token in re.findall(r"0x[0-9a-fA-F]+", table)]
    if len(values) != 3 * 929:
        raise RuntimeError(f"Expected 2787 PDF417 patterns, found {len(values)}")
    lines = [
        "// Generated by tools/generate_pdf417_tables.py.",
        "// Source: go-zpl/internal/pdf417/codewords.go (MIT, derived from boombuler/barcode).",
        "inline constexpr std::array<std::array<int,929>,3> pdf417CodewordPatterns{{",
    ]
    for cluster in range(3):
        lines.append("  std::array<int,929>{")
        row = values[cluster * 929:(cluster + 1) * 929]
        for offset in range(0, len(row), 12):
            lines.append("    " + ",".join(f"0x{value:x}" for value in row[offset:offset + 12]) + ",")
        lines.append("  },")
    lines.append("}};")
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Generated {args.output} with {len(values)} patterns")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
