#!/usr/bin/env python3
"""Generate MaxiCode ISO placement/character tables from go-zpl's MIT source."""

from __future__ import annotations

import argparse
from pathlib import Path
import re


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = PROJECT_ROOT.parent / "go-zpl" / "internal" / "maxicode" / "maxicode.go"
DEFAULT_OUTPUT = PROJECT_ROOT / "src" / "maxicode_tables.inc"


def array_values(source: str, name: str) -> list[int]:
    start = source.index(f"var {name} = []int{{")
    body_start = source.index("{", start) + 1
    body_end = source.index("\n}", body_start)
    body = re.sub(r"/\*[\s\S]*?\*/", "", source[body_start:body_end])
    return [int(value) for value in re.findall(r"\b\d+\b", body)]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    source = args.source.read_text(encoding="utf-8")
    tables = [("maxiGrid", 990), ("maxiCodeSet", 256), ("maxiSymbolChar", 256)]
    output = [
        "// Generated by tools/generate_maxicode_tables.py.",
        "// Source: go-zpl/internal/maxicode/maxicode.go (MIT, forked from ingridhq/maxicode).",
    ]
    for name, expected in tables:
        values = array_values(source, name)
        if len(values) != expected:
            raise RuntimeError(f"Expected {expected} values for {name}, found {len(values)}")
        output.append(f"inline constexpr std::array<int,{expected}> {name}{{")
        for offset in range(0, expected, 20):
            output.append("  " + ",".join(map(str, values[offset:offset + 20])) + ",")
        output.append("};")
    args.output.write_text("\n".join(output) + "\n", encoding="utf-8", newline="\n")
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
